export { default as Home } from "./Home"
export { default as Photography } from "./Photography"
export {default as Coding} from "./Coding"
export {default as Contact} from "./Contact"
export {default as Wedgina} from "./game"
